# Generated by Django 2.2 on 2020-12-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame1_first', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('frame1_second', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('frame2_first', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('frame2_second', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('total_score', models.IntegerField(blank=True, default=0, null=True)),
                ('all_frame_score', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
