# Generated by Django 2.2 on 2020-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0002_auto_20201220_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='frames',
            name='player_name',
            field=models.CharField(default='Player', max_length=150, unique=True),
        ),
    ]
